"""Fixed

Revision ID: 4528e25bd848
Revises: cd201c64ca88
Create Date: 2025-03-17 19:09:23.836809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4528e25bd848'
down_revision = 'cd201c64ca88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'date_created')
    # ### end Alembic commands ###
