"""Fuxed

Revision ID: cd201c64ca88
Revises: 
Create Date: 2025-03-17 18:59:42.284895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd201c64ca88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('current_price', sa.Float(precision=100), nullable=False),
    sa.Column('previous_price', sa.Float(precision=100), nullable=False),
    sa.Column('in_stock', sa.Integer(), nullable=False),
    sa.Column('product_picture', sa.String(length=100), nullable=False),
    sa.Column('flash_sale', sa.Boolean(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('customer_link', sa.Integer(), nullable=False),
    sa.Column('product_link', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_link'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['product_link'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('customer_link', sa.Integer(), nullable=False),
    sa.Column('product_link', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_link'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['product_link'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_link', sa.Integer(), nullable=False),
    sa.Column('product_link', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_link'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['product_link'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist')
    op.drop_table('order')
    op.drop_table('cart')
    op.drop_table('product')
    op.drop_table('customer')
    # ### end Alembic commands ###
