"""Removed payment_id from Order model

Revision ID: cd201c64ca88
Revises: 849ce7675f3d
Create Date: 2025-03-05 16:07:38.288266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd201c64ca88'
down_revision = '849ce7675f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
